#!/bin/bash
# Settings Reboot
clear
if [ ! -e /usr/local/bin/lemon_zaza ]; then
	echo '#!/bin/bash' > /usr/local/bin/lemon_zaza
	echo '' >> /usr/local/bin/lemon_zaza
	echo 'DATE=$(date +"%m-%d-%Y")' >> /usr/local/bin/lemon_zaza
	echo 'TIME=$(date +"%T")' >> /usr/local/bin/lemon_zaza
	echo 'echo "รีบูตเมื่อวันที่ $DATE เวลา $TIME" >> /usr/local/bin/reboot-log' >> /usr/local/bin/lemon_zaza
	echo '/sbin/shutdown -r now' >> /usr/local/bin/lemon_zaza
	chmod +x /usr/local/bin/lemon_zaza
fi

echo -e ""
echo -e " Settings Reboot "
echo -e ""
echo -e "\033[1;31m ➢ \033[0;37m 1 \033[1;32m• \033[1;31m[  รีบูตทุกๆ  1 ชั่วโมง  \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 2 \033[1;32m• \033[1;31m[  รีบูตทุกๆ  2 ชั่วโมง  \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 3 \033[1;32m• \033[1;31m[  รีบูตทุกๆ  12 ชั่วโมง\033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 4 \033[1;32m• \033[1;31m[  รีบูตทุกๆ  1 วัน       \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 5 \033[1;32m• \033[1;31m[  รีบูตทุกๆ  7 วัน       \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 6 \033[1;32m• \033[1;31m[  รีบูตทุกๆ  30 วัน     \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 7 \033[1;32m• \033[1;31m[  ดูการรีบูตบันทึก     \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 8 \033[1;32m• \033[1;31m[  ลบการรีบูต             \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;37m 9 \033[1;32m• \033[1;31m[  กลับ                       \033[1;31m]"
echo -e "\033[1;31m ➢ \033[0;31m x \033[1;32m• \033[1;31m[  กลับไปเมนูหลัก      \033[1;31m]"
echo -e ""
read -p "              เลือกใช้รายการที่ [1-9 or x] : " Start_reboot
echo -e "" 
clear
case $Start_reboot in
		1)
		clear
		echo "10 * * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "                   ตั้งค่ารีบูตอัตโนมัติทุกๆ 1 ชั่วโมงเรียบร้อย   "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		2)
		clear
		echo "10 */6 * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "                  ตั้งค่ารีบูตอัตโนมัติทุกๆ 6 ชั่วโมงเรียบร้อย "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		3)
		clear
		echo "10 */12 * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "                  ตั้งค่ารีบูตอัตโนมัติทุกๆ 12 ชั่วโมงเรียบร้อยแล้ว"
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		4)
		clear
		echo "10 0 * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "                    ตั้งค่ารีบูตอัตโนมัติทุกๆ 1 วันเรียบร้อย  "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		5)
		clear
		echo "10 0 */7 * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "                   ตั้งค่ารีบูตอัตโนมัติทุกๆ 7 วันเรียบร้อย  "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		6)
		clear
		echo "10 0 1 * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e "
		echo -e "                   ตั้งค่ารีบูตอัตโนมัติทุกๆ 30 วันเรียบร้อย "
		echo -e "
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		7)
		clear
		if [ ! -e /root/reboot-log ]; then
	         echo -e ""
			 echo -e "                    ไม่พบการรีบูต    "
			 echo -e ""
             read -sp " กด Enter เพื่อย้อนกลับ"
             echo ""
             SetReboot
	         else
		     echo -e ""
			 echo -e "                          ดูบันทึกรีบูต         "
			 echo -e ""
			 cat /root/reboot-log
			 echo -e ""
             read -sp " กด Enter เพื่อย้อนกลับ"
             echo ""
             SetReboot
        fi
		exit
		;;
		8)
		clear
		rm -f /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "                       ลบการรีบูตอัตโนมัติแล้ว      "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		9)
		clear
		settings_reboot
		exit
		;;
		x)
		clear
		00
		;;
		*)
        SetReboot
		;;
	esac
