#!/bin/bash
# Settings Reboot
clear
if [ ! -e /usr/local/bin/lemon_zaza ]; then
	echo "#!/bin/bash" > /usr/local/bin/lemon_zaza
        echo 'Day_B=$(date +"%d-%m-%Y")' >> /usr/local/bin/lemon_zaza 
	echo 'Time_B=$(date +"%T")' >> /usr/local/bin/lemon_zaza 
	echo 'echo -e "              Reboot เมื่อวันที่ $Day_B เวลา $Time_B." >> /root/reboot-log.txt' >> /usr/local/bin/lemon_zaza 
	echo ""
	echo '/sbin/shutdown -r now' >> /usr/local/bin/lemon_zaza 
	chmod +x /usr/local/bin/lemon_zaza
fi

echo -e ""
echo -e "    **     SETTINGS REBOOT AUTO  [ SET REBOOT TIME ]   ** "
echo -e ""
echo -e "                 [1] set Reboot  1 ชั่วโมง/hour"
echo -e "                 [2] set Reboot  6 ชั่วโมง/hour"
echo -e "                 [3] set Reboot  12 ชั่วโมง/hour"
echo -e "                 [4] set Reboot  1 วัน/Day"
echo -e "                 [5] set Reboot  7 วัน/Day"
echo -e "                 [6] set Reboot hour  30 วัน/Day"
echo -e "                 [7] บันทึกการ Reboot ระบบ"
echo -e "                 [8] ลบการ Reboot"
echo -e "                 [9] กลับ"
echo -e "                 [x] กลับไปเมนูหลัก"
echo -e ""
read -p "         เลือก menu [1-9 or x] : " Start_reboot
echo -e "" 
clear
case $Start_reboot in
		1)
		clear
		echo "0 * * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "   **   ตั้งค่า Reboot อัตโนมัติทุกๆ 1 ชั่วโมงเรียบร้อย   ** "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		2)
		clear
		echo "0 */6 * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "   **   ตั้งค่า Reboot อัตโนมัติทุกๆ 6 ชั่วโมงเรียบร้อย   ** "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		3)
		clear
		echo "0 */12 * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "   **  ตั้งค่า Reboot อัตโนมัติทุกๆ 12 ชั่วโมงเรียบร้อยแล้ว  ** "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		4)
		clear
		echo "0 0 * * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "   **   ตั้งค่า Reboot อัตโนมัติทุกๆ 1 วันเรียบร้อย   ** "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		5)
		clear
		echo "0 0 */7 * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "   **   ตั้งค่า Reboot อัตโนมัติทุกๆ 7 วันเรียบร้อย   ** "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		6)
		clear
		echo "0 0 1 * * root /usr/local/bin/lemon_zaza" > /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "   **    ตั้งค่า Reboot อัตโนมัติทุกๆ 30 วันเรียบร้อย    ** "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		7)
		clear
		if [ ! -e /root/reboot-log.txt ]; then
	         echo -e ""
			 echo -e "       **   ไม่พบการ Reboot!! ( ยังไม่มีการ Reboot ใดๆ )   ** "
			 echo -e ""
             read -sp " กด Enter เพื่อย้อนกลับ"
             echo ""
             SetReboot
	         else
		     echo -e ""
			 echo -e "       **    บันทึก :  สถานะ Reboot ในช่วงวันที่และเวลา    **   "
			 echo -e ""
			 cat /root/reboot-log.txt
			 echo -e ""
             read -sp " กด Enter เพื่อย้อนกลับ"
             echo ""
             SetReboot
        fi
		exit
		;;
		8)
		clear
		rm -f /etc/cron.d/lemon_zaza
		echo -e ""
		echo -e "   **   ลบการ Reboot อัตโนมัติแล้ว   ** "
		echo -e ""
        read -sp " กด Enter เพื่อย้อนกลับ"
        echo ""
        SetReboot
        ;;
		9)
		clear
		06
		exit
		;;
		x)
		clear
		00
		;;
		*)
        SetReboot
		;;
	esac
