#!/bin/bash

NC='\033[0m'

sudo ufw default allow incoming
sudo ufw default allow outgoing
sudo yes | ufw enable

echo -e ""
echo -e ""
echo -e "\033[1;37m  ปิดใช้งาน UFW \033[1;32m OK.\033[1;31m :\033[1;32m 00"
echo -e ""
echo -e ""
echo -ne " \033[1;33m?\033[1;37m${NC} "
